### ISSUE TITLE
Drones leaving medical beds during operations

### ISSUE THREAD

**Issue by LoGInAnNonymous** [RWDevathon/Mechanical-Humanlikes-Core#10]
Issue:

Simple minded drones who do not have bed rest or patient as a work priority just stand up mid operations and there is no way to prevent this, they do not get any sort of "anysthetic", even restricting their zone to only a medical bed will still make them stand up for self maintenance or just straight up "wandering".

Steps to recreate:

Attempt any operation on a drone with no job priority for bed rest or patient, even restrict them to certain places and attempt an operation.

Suggestions to fix:
I personally have never coded in any way so forgive my errors, however I think forcing them to have the "bed rest" and "patient" work priority with no complexity for these work types will fix it.

**Comment by RWDevathon** [comment]
Thank you for the bug report! The issue was in Mechanical Humanlikes: Drones Reprogrammed and has (hopefully) been identified and rooted out. The fix has been pushed to the appropriate GitHub, and will go out to steam with the next batch of updates (no estimated date at this time admittedly). If you would like, you can use the updated version from the GitHub which has the fix in the mean time.

**Comment by LoGInAnNonymous** [comment]
Thank you for the swift response and fix, and thanks for the amazing mod, o7
